In [1]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('raw_data.csv')

In [15]:
# show all the columns of df
pd.set_option("display.max_columns", None)

# Cleaning table from unsued columns
df = df.drop(columns=[
'Favorite',
'Avg Run Cadence',
'Max Run Cadence',
'Avg Stride Length', 
'Avg Vertical Ratio',
'Avg Vertical Oscillation', 
'Avg Ground Contact Time',
'Grit', 
'Flow',
'Avg. Swolf',
'Avg Stroke Rate', 
'Total Reps', 
'Dive Time',
'Surface Interval', 
'Decompression', 
'Best Lap Time', 
'Number of Laps',
'Max Temp']
)

# replacing bulshit values to zeros
df = df.replace(['--'],'')

# converting columns into useful formats
df['Date'] = pd.to_datetime(df['Date'])
df['Distance'] = df['Distance'].str.replace(',', '.').astype('float')
df['Calories'] = df['Calories'].str.replace('.', '').astype('float')
df['Avg HR'] = df['Avg HR'].astype('int')
df['Max HR'] = df['Max HR'].astype('int')
df['Aerobic TE'] = df['Aerobic TE'].str.replace(',', '.').astype('float')
df['Avg Speed'] = df['Avg Speed'].str.replace(',', '.').astype('float')
df['Max Speed'] = df['Max Speed'].str.replace(',', '.').astype('float')
df['Total Ascent'] = df['Total Ascent'].str.replace('.', '').astype('int')
df['Total Descent'] = df['Total Descent'].str.replace('.', '').astype('int')
df['Avg Bike Cadence'] = df['Avg Bike Cadence'].astype('int')
df['Max Bike Cadence'] = df['Max Bike Cadence'].astype('int')
df['Normalized Power® (NP®)'] = df['Normalized Power® (NP®)'].astype('int')
df['Training Stress Score®'] = df['Training Stress Score®'].str.replace(',', '.').astype('float')
df['Max Avg Power (20 min)'] = df['Max Avg Power (20 min)'].str.replace(',', '.').astype('int')
df['Avg Power'] = df['Avg Power'].str.replace(',', '.').astype('int')
df['Max Power'] = df['Max Power'].str.replace(',', '.').astype('int')
df['Total Strokes'] = df['Total Strokes'].str.replace(',', '.').astype('int')
df['Min Temp'] = df['Min Temp'].str.replace(',', '.').astype('float')
df['Min Elevation'] = df['Min Elevation'].str.replace('.', '').astype('int')
df['Max Elevation'] = df['Max Elevation'].str.replace('.', '').astype('int')
df['Time'] = pd.to_timedelta(df['Time'])
df['Moving Time'] = pd.to_timedelta(df['Moving Time'])
df['Elapsed Time'] = pd.to_timedelta(df['Elapsed Time'])

# rename columns
df.rename(
    columns={
        'Activity Type': 'Activity_Type',
        'Avg HR': 'Avg_HR',
        'Max HR': 'Max_HR',
        'Aerobic TE': 'Aerobic_TE',
        'Avg Speed': 'Avg_Speed',
        'Max Speed': 'Max_Speed',
        'Total Ascent': 'Total_Ascent',
        'Total Descent': 'Total_Descent',
        'Avg Bike Cadence': 'Avg_Cadence',
        'Max Bike Cadence': 'Max_Cadence',
        'Normalized Power® (NP®)': 'Normalized_Power',
        'Training Stress Score®': 'Training_Stress_Score',
        'Max Avg Power (20 min)': 'Max_Avg_Power(20min)',
        'Avg Power': 'Avg_Power',
        'Max Power': 'Max_Power',
        'Total Strokes': 'Total_Strokes',
        'Min Temp': 'Min_Temp',
        'Moving Time': 'Moving_Time',
        'Elapsed Time': 'Elapsed_Time',
        'Min Elevation': 'Min_Elevation',
        'Max Elevation': 'Max_Elevation'
    }, inplace=True
)

# create new column with name of bike used
# create a list of our conditions
conditions = [
    (df['Activity_Type'] == 'Road Cycling'),
    (df['Activity_Type'] == 'Gravel/Unpaved Cycling'),
    (df['Activity_Type'] == 'Mountain Biking'),
    (df['Activity_Type'] == 'Indoor Cycling'),
    (df['Activity_Type'] == 'Virtual Cycling'),
    (df['Activity_Type'] == 'Cycling')
]
# create a list of the values we want to assign for each condition
values = ['Roubaix', 'Bergamont', 'Rockhopper', 'Tacx', 'Tacx', 'unknown']
# create a new column and use np.select to assign values to it using our lists as arguments
df['Bike'] = np.select(conditions, values)

C:\Users\Radim Jedlicka\AppData\Local\Temp/ipykernel_21400/2386537272.py:32: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Calories'] = df['Calories'].str.replace('.', '').astype('float')

ValueError: could not convert string to float: ''

In [16]:
df

,Activity Type,Date,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,Avg Speed,Max Speed,Total Ascent,Total Descent,Avg Bike Cadence,Max Bike Cadence,Normalized Power® (NP®),Training Stress Score®,Max Avg Power (20 min),Avg Power,Max Power,Total Strokes,Min Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Gravel/Unpaved Cycling,2022-09-04 14:07:00,Praha - Kotce,104.80,2.744,4:11:44,150,183,"5,0","25,0","51,0",755,929,0,0,,"0,0",,0,0,,"20,0",4:11:00,4:37:56,170,382
1,Gravel/Unpaved Cycling,2022-09-03 14:33:00,Lomnice s Karin,24.86,688,1:23:07,122,159,"2,4","17,9","52,2",403,404,0,0,,"0,0",,0,0,,"18,0",1:22:39,1:38:46,294,558
2,Road Cycling,2022-08-27 09:44:00,Trento and back,101.84,2.341,3:44:49,141,176,"4,1","27,2","60,0",565,569,82,125,,"0,0",,0,0,17350,"17,0",3:44:41,3:51:45,203,569
3,Road Cycling,2022-08-24 10:09:00,Mittelberg + Passo Mendola,61.69,2.373,2:50:10,158,185,"5,0","21,7","57,9",1.177,1.173,77,122,,"0,0",,0,0,11219,"23,0",2:50:01,3:05:51,227,1.346
4,Road Cycling,2022-08-22 08:41:00,Mittelberg 2022_3,40.76,1.251,1:36:25,148,183,"4,1","25,4","54,7",441,433,83,123,,"0,0",,0,0,7143,"19,0",1:36:22,1:39:16,222,576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,Cycling,2012-07-29 10:16:00,Černá Hora circle,34.00,1.39,2:24:53,150,179,,"14,1","55,8",1.184,1.215,0,0,,"0,0",,0,0,,"0,0",0:00:00,0:00:00,,
751,Cycling,2012-07-09 19:46:00,Berghaus,14.24,859,1:54:10,0,0,,"7,5","49,9",408,683,0,0,,"0,0",,0,0,,"0,0",0:00:00,0:00:00,,
752,Cycling,2012-07-05 09:08:00,Z chaty do Monkey Parku,1.57,116,0:06:40,0,0,,"14,2","17,6",49,13,0,0,,"0,0",,0,0,,"0,0",0:00:00,0:00:00,,
753,Cycling,2012-07-04 20:08:00,Z Horizontu do chaty,1.67,76,0:03:24,0,0,,"29,5","60,1",42,83,0,0,,"0,0",,0,0,,"0,0",0:00:00,0:00:00,,
754,Cyclocross,2012-07-04 13:24:00,Okolo Pece,7.77,491,0:53:17,0,0,,"8,7","40,4",269,272,0,0,,"0,0",,0,0,,"0,0",0:00:00,0:00:00,,

In [17]:
df['Date'].dt.year

0      2022
1      2022
2      2022
3      2022
4      2022
       ...
750    2012
751    2012
752    2012
753    2012
754    2012
Name: Date, Length: 755, dtype: int64

In [18]:
km_per_year = df[['Distance']].groupby(df['Date'].dt.year).sum()
km_per_year

      Distance
Date
2012     59.25
2014   1226.46
2015    896.64
2016   1006.86
2017   2124.19
2018   5670.12
2019   5034.08
2020   7505.82
2021   6703.34
2022   3131.26

In [19]:
df[['Date', 'Bike', 'Distance']].groupby(df['Date'].dt.year).agg({'Distance': 'sum'})

KeyError: "['Bike'] not in index"

In [10]:
(df
    .query(str(['Date'].dt.year) == 2022')
    [['Distance', 'Bike']]
    .assign('Distance')
    .groupby([['Date'].dt.year, 'Bike'])
    .sum()
    )

SyntaxError: unterminated string literal (detected at line 2) (Temp/ipykernel_11124/3594909379.py, line 2)